/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ir.srn.ipl.jvircam;

import javax.swing.JSpinner;
import javax.vecmath.Matrix3d;
import javax.vecmath.Matrix4d;

/**
 *
 * @author sr
 */
public class KMatrix extends javax.swing.JFrame {

    private Projection projection;
    private ImagePanel imagePanel;

    /**
     * Creates new form KMatrix
     */
    public KMatrix(Projection projection, ImagePanel imagePanel) {
        initComponents();
        this.projection = projection;
        this.imagePanel = imagePanel;
    }

    public void setMatrix(Matrix3d k) {
        this.spinner11.setValue(k.m00);
        this.spinner12.setValue(k.m01);
        this.spinner13.setValue(k.m02);
        //
        this.spinner21.setValue(k.m10);
        this.spinner22.setValue(k.m11);
        this.spinner23.setValue(k.m12);
        //
        this.spinner31.setValue(k.m20);
        this.spinner32.setValue(k.m21);
        this.spinner33.setValue(k.m22);
        //        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spinner11 = new javax.swing.JSpinner();
        spinner12 = new javax.swing.JSpinner();
        spinner13 = new javax.swing.JSpinner();
        spinner21 = new javax.swing.JSpinner();
        spinner22 = new javax.swing.JSpinner();
        spinner23 = new javax.swing.JSpinner();
        spinner31 = new javax.swing.JSpinner();
        spinner32 = new javax.swing.JSpinner();
        spinner33 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("K Matrix");

        spinner11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner11StateChanged(evt);
            }
        });

        spinner12.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner12StateChanged(evt);
            }
        });

        spinner13.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner13StateChanged(evt);
            }
        });

        spinner21.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner21StateChanged(evt);
            }
        });

        spinner22.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner22StateChanged(evt);
            }
        });

        spinner23.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner23StateChanged(evt);
            }
        });

        spinner31.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner31StateChanged(evt);
            }
        });

        spinner32.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner32StateChanged(evt);
            }
        });

        spinner33.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner33StateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spinner11, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(spinner21)
                    .addComponent(spinner31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spinner12, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(spinner22)
                    .addComponent(spinner32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spinner13, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(spinner23)
                    .addComponent(spinner33))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinner11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinner21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinner31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinner11StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner11StateChanged
        Matrix3d k = projection.getK();
        k.m00 = ((Double.parseDouble(((JSpinner) evt.getSource()).getModel().getValue().toString())));
        projection.set(new Projection(k, projection.getR(), projection.getT()));
        imagePanel.repaint();
    }//GEN-LAST:event_spinner11StateChanged

    private void spinner12StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner12StateChanged
        Matrix3d k = projection.getK();
        k.m01 = ((Double.parseDouble(((JSpinner) evt.getSource()).getModel().getValue().toString())));
        projection.set(new Projection(k, projection.getR(), projection.getT()));
        imagePanel.repaint();
    }//GEN-LAST:event_spinner12StateChanged

    private void spinner13StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner13StateChanged
        Matrix3d k = projection.getK();
        k.m02 = ((Double.parseDouble(((JSpinner) evt.getSource()).getModel().getValue().toString())));
        projection.set(new Projection(k, projection.getR(), projection.getT()));
        imagePanel.repaint();
    }//GEN-LAST:event_spinner13StateChanged

    private void spinner21StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner21StateChanged
        Matrix3d k = projection.getK();
        k.m10 = ((Double.parseDouble(((JSpinner) evt.getSource()).getModel().getValue().toString())));
        projection.set(new Projection(k, projection.getR(), projection.getT()));
        imagePanel.repaint();
    }//GEN-LAST:event_spinner21StateChanged

    private void spinner22StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner22StateChanged
        Matrix3d k = projection.getK();
        k.m11 = ((Double.parseDouble(((JSpinner) evt.getSource()).getModel().getValue().toString())));
        projection.set(new Projection(k, projection.getR(), projection.getT()));
        imagePanel.repaint();
    }//GEN-LAST:event_spinner22StateChanged

    private void spinner23StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner23StateChanged
        Matrix3d k = projection.getK();
        k.m12 = ((Double.parseDouble(((JSpinner) evt.getSource()).getModel().getValue().toString())));
        projection.set(new Projection(k, projection.getR(), projection.getT()));
        imagePanel.repaint();
    }//GEN-LAST:event_spinner23StateChanged

    private void spinner31StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner31StateChanged
        Matrix3d k = projection.getK();
        k.m20 = ((Double.parseDouble(((JSpinner) evt.getSource()).getModel().getValue().toString())));
        projection.set(new Projection(k, projection.getR(), projection.getT()));
        imagePanel.repaint();
    }//GEN-LAST:event_spinner31StateChanged

    private void spinner32StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner32StateChanged
        Matrix3d k = projection.getK();
        k.m21 = ((Double.parseDouble(((JSpinner) evt.getSource()).getModel().getValue().toString())));
        projection.set(new Projection(k, projection.getR(), projection.getT()));
        imagePanel.repaint();
    }//GEN-LAST:event_spinner32StateChanged

    private void spinner33StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner33StateChanged
        Matrix3d k = projection.getK();
        k.m22 = ((Double.parseDouble(((JSpinner) evt.getSource()).getModel().getValue().toString())));
        projection.set(new Projection(k, projection.getR(), projection.getT()));
        imagePanel.repaint();
    }//GEN-LAST:event_spinner33StateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner spinner11;
    private javax.swing.JSpinner spinner12;
    private javax.swing.JSpinner spinner13;
    private javax.swing.JSpinner spinner21;
    private javax.swing.JSpinner spinner22;
    private javax.swing.JSpinner spinner23;
    private javax.swing.JSpinner spinner31;
    private javax.swing.JSpinner spinner32;
    private javax.swing.JSpinner spinner33;
    // End of variables declaration//GEN-END:variables
}
